### ISSUE TITLE
pixel classification

### ISSUE THREAD

**Issue by hackermd** [TissueMAPS/TmLibrary#18]
Let's create a new workflow step for pixel classification based on [Ilastik](https://github.com/ilastik/ilastik/tree/master). The step should be able to apply a classifier trained via the _Ilastik_ GUI (saved to disk as _.ilp_ file) to a set of images and output a probability map (_.png_ file) for each image.

This should be implemented as a step of the _image_preprocessing_ stage using _Ilastik_ in _headless_ mode via the command line. It is only a temporary solution, however. Ultimately, the classifier should be applied to an image directly in Python, which should be implemented as a Jterator module, see TissueMAPS/JtLibrary#4.

**Comment by riccardomurri** [comment]
This issue was moved to TissueMAPS/TissueMAPS#122
