### ISSUE TITLE
Rolling up aggregation of feature values

### ISSUE THREAD

**Issue by hackermd** [TissueMAPS/TmLibrary#33]
Since feature values are stored in an `HSTORE` column, the database doesn't collect statistics about the values. This makes it difficult to quickly obtain statistics, such as the `min` or `max` values. To facilitate such queries in real-time we could compute and store aggregates for feature values ahead of time. See [Citus docs](https://docs.citusdata.com/en/v6.1/dist_tables/dml.html#distributed-aggregations).

**Comment by riccardomurri** [comment]
This issue was moved to TissueMAPS/TissueMAPS#124
